###
POST http://localhost:8000/account
Content-Type: "application/json"

{
    "owner": "Tho Pham",
    "currency": "ASD"
}

###
GET http://localhost:8000/account/1

###
GET http://localhost:8000/accounts?page=2&&page_size=10
###
PUT  http://localhost:8000/account/322
Content-Type: "application/json"

{
    "owner": "Update Account",
    "balance": 100,
    "currency": "USD"
}
###
DELETE  http://localhost:8000/account/2

###
POST http://localhost:8000/transfer
Content-Type: "application/json"

{
    "from_account_id": 9,
    "to_account_id": 10,
    "amount": 100,
    "currency": "USD"
}

###
POST http://localhost:8000/user
Content-Type: "application/json"

{
    "user_name": "tholgbg2",
    "password": "secret",
    "full_name": "Tho Pham",
    "email": "tholgbg2@gmail.com"
}