// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: tranfer.sql

package db

import (
	"context"
)

const createTranfer = `-- name: CreateTranfer :one
INSERT INTO tranfers (
  from_account_id,
  to_account_id,
  amount
) VALUES (
  $1, $2, $3
) RETURNING id, from_account_id, to_account_id, amount, create_at
`

type CreateTranferParams struct {
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	Amount        int64 `json:"amount"`
}

func (q *Queries) CreateTranfer(ctx context.Context, arg CreateTranferParams) (Tranfer, error) {
	row := q.db.QueryRowContext(ctx, createTranfer, arg.FromAccountID, arg.ToAccountID, arg.Amount)
	var i Tranfer
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.CreateAt,
	)
	return i, err
}

const deleteTranfer = `-- name: DeleteTranfer :exec
DELETE FROM tranfers WHERE id = $1
`

func (q *Queries) DeleteTranfer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTranfer, id)
	return err
}

const getTranfer = `-- name: GetTranfer :one
SELECT id, from_account_id, to_account_id, amount, create_at FROM tranfers
WHERE id = $1
`

func (q *Queries) GetTranfer(ctx context.Context, id int64) (Tranfer, error) {
	row := q.db.QueryRowContext(ctx, getTranfer, id)
	var i Tranfer
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.CreateAt,
	)
	return i, err
}

const listTranfers = `-- name: ListTranfers :many
SELECT id, from_account_id, to_account_id, amount, create_at FROM tranfers
ORDER BY id
`

func (q *Queries) ListTranfers(ctx context.Context) ([]Tranfer, error) {
	rows, err := q.db.QueryContext(ctx, listTranfers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tranfer
	for rows.Next() {
		var i Tranfer
		if err := rows.Scan(
			&i.ID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.Amount,
			&i.CreateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTranfer = `-- name: UpdateTranfer :exec
UPDATE tranfers
SET from_account_id = $2, to_account_id = $3, amount = $4
WHERE id = $1
`

type UpdateTranferParams struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	Amount        int64 `json:"amount"`
}

func (q *Queries) UpdateTranfer(ctx context.Context, arg UpdateTranferParams) error {
	_, err := q.db.ExecContext(ctx, updateTranfer,
		arg.ID,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Amount,
	)
	return err
}
